
on:
 workflow_dispatch:
  inputs:
   no_deps:
    description: "request dependencies"
env:
 #for upload
 GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
 archbuild:
  runs-on: ubuntu-latest
  container: archlinux:latest

  steps:
  - name: Checkout
    uses: actions/checkout@master
  - name: build
    run: |
     name=`cat debian/changelog | head -1 | grep -o ^[^\ ]*`
     here=`pwd`

     useradd bot
     cd /home
     mkdir bot
     chown bot:bot bot
     cd bot
     pacman -Sy --noconfirm --needed sudo git base-devel wget\
      python-build python-installer python-wheel python-setuptools

     command=makepkg
     if [ -z "${{ github.event.inputs.no_deps }}" ]; then
      pacman -Sy --noconfirm --needed gtk4 python-appdirs python-psutil python-gobject python-requests

      echo "ALL ALL=(ALL) NOPASSWD: /usr/bin/*" > /etc/sudoers.d/a  #needed at makepkg -i and yay makepkg calls

      su bot -c 'git clone --depth 1 https://aur.archlinux.org/yay-bin.git'
      cd yay-bin
      su bot -c 'makepkg -i --noconfirm'

      su bot -c 'yay -Sy --noconfirm --needed eiskaltdcpp-daemon' || { #will fail
       cd ../.cache/yay/eiskaltdcpp
       patch --input="${here}/arh/eispatch"
       su bot -c "makepkg -ei --noconfirm"

       eisver=`cat ./PKGBUILD | grep ^pkgver= | grep -Po '(?<==).*'`
       eisrel=`cat ./PKGBUILD | grep ^pkgrel= | grep -Po '(?<==).*'`
       echo ${eisver}-${eisrel} > ${here}/eisversion
       eismajorver=`echo ${eisver} | grep -o ^[0-9]*.[0-9]*`
       mkdir eiskaltdcpp-daemon
       mv src/build/eiskaltdcpp-daemon/eiskaltdcpp-daemon eiskaltdcpp-daemon
       mv src/build/dcpp/libeiskaltdcpp.so.${eismajorver} eiskaltdcpp-daemon
       tar -c -f ${here}/eiskaltdcpp-daemon.tar eiskaltdcpp-daemon
       #--zstd
       zstd ${here}/eiskaltdcpp-daemon.tar
      }
     else
      command="${command} --nodeps"
     fi

     fullname=python-${name}

     su bot -c 'git clone -n --depth=1 --filter=tree:0 https://github.com/colin-i/pkgbuilds'
     cd pkgbuilds
     su bot -c "git sparse-checkout set --no-cone /${fullname}"
     su bot -c 'git checkout'

     cd ${fullname}
     su bot -c "${command}"

     nm=`ls | grep ".*\.zst$" | grep -v debug`
     nm2=`echo ${nm} | sed s/-any/-all/`
     mv ${nm} ${here}/${nm2}
     echo "file=${nm2}" >> $GITHUB_ENV

     wget https://github.com/colin-i/test/releases/download/1.5/${name} -O 1.txt
     echo "up_url=`cat 1.txt`" >> $GITHUB_ENV
  - name: Upload Release Asset
    uses: actions/upload-release-asset@v1
    with:
     upload_url: ${{ env.up_url }}
     asset_path: ./${{ env.file }}
     asset_name: ${{ env.file }}
     asset_content_type: application/zstd
  - name: Upload Release Asset eis kalt
    if: ${{ github.event.inputs.no_deps == '' }}
    uses: actions/upload-release-asset@v1
    with:
     upload_url: https://uploads.github.com/repos/colin-i/eiskaltdcpp/releases/228049606/assets{?name,label}
     asset_path: ./eiskaltdcpp-daemon.tar.zst
     asset_name: eiskaltdcpp-daemon.tar.zst
     asset_content_type: application/zstd
  - name: Upload Release Asset eis kalt version
    if: ${{ github.event.inputs.no_deps == '' }}
    uses: actions/upload-release-asset@v1
    with:
     upload_url: https://uploads.github.com/repos/colin-i/eiskaltdcpp/releases/228049606/assets{?name,label}
     asset_path: ./eisversion
     asset_name: version
     asset_content_type: text/plain
